name: Node.js CI

on:
  push:
    branches:
      - prod
      - 'feature/**'
      - 'hotfix/**'
  pull_request:
    branches:
      - prod

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 11.x
      uses: actions/setup-node@v1
      with:
        node-version: '11.x'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - run: npm run lint
